version: "3.2"
services:
  postgres-dev:
    build:
      context: ../../../
      dockerfile: ./postgres/Dockerfile
    container_name: postgres-dev
    environment:
      POSTGRES_DB: think-platform
      POSTGRES_USER: think
      POSTGRES_PASSWORD: think
    expose:
      - "5436"
    ports:
      - "5436:5436"
    command: -p 5436

  back-server-dev:
    build:
      context: ../../../
      dockerfile: ./projects/back/dev/Dockerfile
    container_name: back-server-dev
    ports:
      - "5559:5559"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-release:5436/think-platform
      SPRING_DATASOURCE_USERNAME: think
      SPRING_DATASOURCE_PASSWORD: think
      SERVER_PORT: 5559
    depends_on:
      - postgres-dev
